apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-mulit-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: chrisvaldez.dev
  dnsNames:
    - chrisvaldez.dev
    - www.chrisvaldez.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - chrisvaldez.dev
          - www.chrisvaldez.dev
